<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>experiment_logger</name>
  <version>1.0.0</version>
  <description>ROS2 CSV logger for traj_cmd and synced payload pose streams</description>
  <maintainer email="sanjay@lsu.edu">Sanjay</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>gantry_control</exec_depend>
  <exec_depend>payload_perception_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
